version: "3.8"

services:
  # nginx
  nginx:
    container_name: "${PROJECT_NAME}-nginx-latest"
    image: "nginx"
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ../www:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php

  # php
  php:
    build: ./php
    container_name: "${PROJECT_NAME}-php-7.4-fpm"
    image: "php-7.4-fpm"
    volumes:
      - ../www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
